POST http://localhost:3333/add HTTP/1.1
Content-Type: application/json

{
    "name": "Test Testando",
    "opinion": "Educa Moçambique Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore quisquam sit beatae ratione expedita. Iure iusto eligendi suscipit natus alias excepturi sint neque maxime repellendus, quas quia animi enim? Laboriosam. Lorem ipsum dolor sit amet consect",
    "status": "Deslike"
}

###
POST http://localhost:3333/event_data HTTP/1.1
Content-Type: application/json

{
    "event_name": "Educa Moçambique",
    "event_about": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore quisquam sit beatae ratione expedita. Iure iusto eligendi suscipit natus alias excepturi sint neque maxime repellendus, quas quia animi enim? Laboriosam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi perferendis praesentium magnam voluptas eaque quas ratione corrupti fugit optio nihil inventore, dolores pariatur eum illum similique, ipsa fuga! Quas, quasi.  amet consectetur adipisicing elit. Inventore quisquam sit beatae ratione expedita. Iure iusto eligendi suscipit natus alias excepturi sint neque maxime repellendus, quas quia animi enim? Laboriosam. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sequi perferendis praesentium magnam voluptas eaque quas ratione corrupti fugit optio nihil inventore, dolores pariatur eum illum similique, ipsa fuga! Quas, quasi.",
    "event_date": "13 de outumbro de 2024"
}

###
DELETE http://localhost:3333/eventdata/9 HTTP/1.1

###
GET http://localhost:3333/rank HTTP/1.1
